### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by thainguyenit** [concordusapps/grunt-haml#17]
How to fix this error? please help me.

> ref@0.1.3 install /Thainguyen/KGU-demo/node_modules/grunt-haml-leahcimic/node_modules/execSync/node_modules/ffi/node_modules/ref
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Thainguyen/KGU-demo/node_modules/grunt-haml-leahcimic/node_modules/execSync/node_modules/ffi/node_modules/ref
gyp ERR! node -v v0.10.16
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by mehcode** [comment]
Ah.. I see the problem.. `node-gyp` exists (for more context .. it's trying to build itself using make and python which don't seem to exist on your system). Give me about ~30 minutes -- I'll get a fix pushed for you. I've been meaning to fix this anyway.

**Comment by mehcode** [comment]
Fixed. Run `npm cache clean` then `npm install grunt-haml` and it should be good to go.

**Comment by thainguyenit** [comment]
Hi Mehcode,
Thank you so much but It still show that error, please check again: 

> ref@0.1.3 install /Thainguyen/KGU-demo/node_modules/grunt-haml-leahcimic/node_modules/execSync/node_modules/ffi/node_modules/ref
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Thainguyen/KGU-demo/node_modules/grunt-haml-leahcimic/node_modules/execSync/node_modules/ffi/node_modules/ref
gyp ERR! node -v v0.10.16
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
Thais-MacBook-Pro:KGU-demo thainguyen$ grunt

> > Local Npm module "grunt-haml-leahcimic" not found. Is it installed?

**Comment by mehcode** [comment]
The error log is saying that you're trying to install `grunt-haml-leahcmic`. That is an old package that was uploaded by @leahcimic. Make sure you're installing **grunt-haml**.

---

Since we're looking at this @leahcimic can you unpublish that package?

**Comment by thainguyenit** [comment]
Hi mehcode,
that is my mistake, now it is ok, thank you for all :)

**Comment by leahciMic** [comment]
Will unpublish

```
—
```

**Comment by mehcode** [comment]
Thank you @leahciMic -- glad you got it working @thainguyenit
